# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/realnfcs/codes/gc/tutorial

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/realnfcs/codes/gc/tutorial

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/realnfcs/codes/gc/tutorial/CMakeFiles /home/realnfcs/codes/gc/tutorial//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/realnfcs/codes/gc/tutorial/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tutorial

# Build rule for target.
Tutorial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tutorial
.PHONY : Tutorial

# fast build rule for target.
Tutorial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/build
.PHONY : Tutorial/fast

libraries/include/glad/src/glad.o: libraries/include/glad/src/glad.c.o
.PHONY : libraries/include/glad/src/glad.o

# target to build an object file
libraries/include/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/libraries/include/glad/src/glad.c.o
.PHONY : libraries/include/glad/src/glad.c.o

libraries/include/glad/src/glad.i: libraries/include/glad/src/glad.c.i
.PHONY : libraries/include/glad/src/glad.i

# target to preprocess a source file
libraries/include/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/libraries/include/glad/src/glad.c.i
.PHONY : libraries/include/glad/src/glad.c.i

libraries/include/glad/src/glad.s: libraries/include/glad/src/glad.c.s
.PHONY : libraries/include/glad/src/glad.s

# target to generate assembly for a file
libraries/include/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/libraries/include/glad/src/glad.c.s
.PHONY : libraries/include/glad/src/glad.c.s

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/EBO.o: src/EBO.cpp.o
.PHONY : src/EBO.o

# target to build an object file
src/EBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/EBO.cpp.o
.PHONY : src/EBO.cpp.o

src/EBO.i: src/EBO.cpp.i
.PHONY : src/EBO.i

# target to preprocess a source file
src/EBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/EBO.cpp.i
.PHONY : src/EBO.cpp.i

src/EBO.s: src/EBO.cpp.s
.PHONY : src/EBO.s

# target to generate assembly for a file
src/EBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/EBO.cpp.s
.PHONY : src/EBO.cpp.s

src/Mesh.o: src/Mesh.cpp.o
.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i
.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s
.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/Model.o: src/Model.cpp.o
.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i
.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s
.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/SDL2.o: src/SDL2.cpp.o
.PHONY : src/SDL2.o

# target to build an object file
src/SDL2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/SDL2.cpp.o
.PHONY : src/SDL2.cpp.o

src/SDL2.i: src/SDL2.cpp.i
.PHONY : src/SDL2.i

# target to preprocess a source file
src/SDL2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/SDL2.cpp.i
.PHONY : src/SDL2.cpp.i

src/SDL2.s: src/SDL2.cpp.s
.PHONY : src/SDL2.s

# target to generate assembly for a file
src/SDL2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/SDL2.cpp.s
.PHONY : src/SDL2.cpp.s

src/Texture.o: src/Texture.cpp.o
.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i
.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s
.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/VAO.o: src/VAO.cpp.o
.PHONY : src/VAO.o

# target to build an object file
src/VAO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/VAO.cpp.o
.PHONY : src/VAO.cpp.o

src/VAO.i: src/VAO.cpp.i
.PHONY : src/VAO.i

# target to preprocess a source file
src/VAO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/VAO.cpp.i
.PHONY : src/VAO.cpp.i

src/VAO.s: src/VAO.cpp.s
.PHONY : src/VAO.s

# target to generate assembly for a file
src/VAO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/VAO.cpp.s
.PHONY : src/VAO.cpp.s

src/VBO.o: src/VBO.cpp.o
.PHONY : src/VBO.o

# target to build an object file
src/VBO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/VBO.cpp.o
.PHONY : src/VBO.cpp.o

src/VBO.i: src/VBO.cpp.i
.PHONY : src/VBO.i

# target to preprocess a source file
src/VBO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/VBO.cpp.i
.PHONY : src/VBO.cpp.i

src/VBO.s: src/VBO.cpp.s
.PHONY : src/VBO.s

# target to generate assembly for a file
src/VBO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/VBO.cpp.s
.PHONY : src/VBO.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/shaderClass.o: src/shaderClass.cpp.o
.PHONY : src/shaderClass.o

# target to build an object file
src/shaderClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/shaderClass.cpp.o
.PHONY : src/shaderClass.cpp.o

src/shaderClass.i: src/shaderClass.cpp.i
.PHONY : src/shaderClass.i

# target to preprocess a source file
src/shaderClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/shaderClass.cpp.i
.PHONY : src/shaderClass.cpp.i

src/shaderClass.s: src/shaderClass.cpp.s
.PHONY : src/shaderClass.s

# target to generate assembly for a file
src/shaderClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/shaderClass.cpp.s
.PHONY : src/shaderClass.cpp.s

src/stb.o: src/stb.cpp.o
.PHONY : src/stb.o

# target to build an object file
src/stb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/stb.cpp.o
.PHONY : src/stb.cpp.o

src/stb.i: src/stb.cpp.i
.PHONY : src/stb.i

# target to preprocess a source file
src/stb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/stb.cpp.i
.PHONY : src/stb.cpp.i

src/stb.s: src/stb.cpp.s
.PHONY : src/stb.s

# target to generate assembly for a file
src/stb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tutorial.dir/build.make CMakeFiles/Tutorial.dir/src/stb.cpp.s
.PHONY : src/stb.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tutorial"
	@echo "... libraries/include/glad/src/glad.o"
	@echo "... libraries/include/glad/src/glad.i"
	@echo "... libraries/include/glad/src/glad.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/EBO.o"
	@echo "... src/EBO.i"
	@echo "... src/EBO.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/SDL2.o"
	@echo "... src/SDL2.i"
	@echo "... src/SDL2.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/VAO.o"
	@echo "... src/VAO.i"
	@echo "... src/VAO.s"
	@echo "... src/VBO.o"
	@echo "... src/VBO.i"
	@echo "... src/VBO.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shaderClass.o"
	@echo "... src/shaderClass.i"
	@echo "... src/shaderClass.s"
	@echo "... src/stb.o"
	@echo "... src/stb.i"
	@echo "... src/stb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

